export const initialPaintings = [
  {
    id: "art-1",
    title: "Cosmic Awakening: Lord Ganesha",
    artist: "Ananya Sen",
    artistBio: "Kolkata-based contemporary master specializing in sacred symbolism and modern abstraction with gold leaf accents.",
    category: "Spiritual & Devotional",
    medium: "Acrylic & 24K Gold Leaf on Linen Canvas",
    style: "Contemporary Spiritual",
    orientation: "vertical",
    dimensions: "36\" x 48\" (91.4 x 121.9 cm)",
    year: 2024,
    price: 48500,
    originalPrice: 65000,
    discount: 25,
    image: "https://images.unsplash.com/photo-1582561424760-0321d75e81fa?auto=format&fit=crop&w=1200&q=80",
    description: "An awe-inspiring interpretation of Lord Ganesha radiating cosmic energy, rendered with intricate textures, vibrant saffron, crimson, and authentic 24K gold foil embellishments. Symbolizes wisdom, prosperity, and the removal of obstacles.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8841",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships rolled safely, ready for your custom framing" },
      { id: "stretched", name: "Stretched Canvas (Gallery Wrapped)", price: 2000, desc: "Canvas stretched over 1.5 inch kiln-dried pine wood bars, ready to hang" },
      { id: "teak_frame", name: "Handcrafted Teakwood Floating Frame", price: 4500, desc: "Luxury natural teakwood floater frame with modern reveal gap" },
      { id: "black_frame", name: "Minimalist Matte Black Frame", price: 3800, desc: "Architectural satin black frame with protective backing" },
      { id: "gold_frame", name: "Royal Antique Gold Leaf Frame", price: 5600, desc: "Opulent hand-gilded heritage frame with textured corners" }
    ],
    roomScale: 1.15
  },
  {
    id: "art-2",
    title: "Varanasi: Dawn on the Holy Ghats",
    artist: "Rajeshwar Sharma",
    artistBio: "Senior impressionist painter celebrated for his luminous portrayals of Indian riverfronts and historic architecture.",
    category: "Landscape & Scenery",
    medium: "Oil on Fine Belgian Linen",
    style: "Impressionist Realism",
    orientation: "horizontal",
    dimensions: "48\" x 32\" (121.9 x 81.3 cm)",
    year: 2024,
    price: 62000,
    originalPrice: 78000,
    discount: 21,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1200&q=80",
    description: "Morning light dancing on the sacred Ganges river as wooden boats drift past centuries-old stone temples. Rich impasto brushstrokes evoke the spiritual mysticism, golden mist, and tranquil awakening of Kashi.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8842",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships rolled safely, ready for your custom framing" },
      { id: "stretched", name: "Stretched Canvas (Gallery Wrapped)", price: 2200, desc: "Canvas stretched over kiln-dried pine wood bars" },
      { id: "teak_frame", name: "Handcrafted Teakwood Floating Frame", price: 4800, desc: "Luxury natural teakwood floater frame" },
      { id: "black_frame", name: "Minimalist Matte Black Frame", price: 4000, desc: "Sleek architectural matte black frame" },
      { id: "gold_frame", name: "Royal Antique Gold Leaf Frame", price: 5900, desc: "Classic ornate museum-grade gilt frame" }
    ],
    roomScale: 1.25
  },
  {
    id: "art-3",
    title: "Symphony in Indigo & Raw Ochre",
    artist: "Kabir V. Mehta",
    artistBio: "Acclaimed non-objective abstractionist whose large scale canvases have been showcased in Mumbai, London, and Dubai.",
    category: "Abstract",
    medium: "Mixed Media & Pumice Texture on Canvas",
    style: "Abstract Expressionism",
    orientation: "square",
    dimensions: "40\" x 40\" (101.6 x 101.6 cm)",
    year: 2024,
    price: 54000,
    originalPrice: 68000,
    discount: 21,
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1200&q=80",
    description: "A commanding dialogue between deep indigo blues, warm natural earth tones, and sharp rhythmic scrapings. The heavy sculptural texture captures ambient lighting dramatically, making it a showstopper for modern spaces.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8843",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships rolled safely, ready for your custom framing" },
      { id: "stretched", name: "Stretched Canvas (Gallery Wrapped)", price: 2000, desc: "Canvas stretched over kiln-dried pine wood bars" },
      { id: "teak_frame", name: "Handcrafted Teakwood Floating Frame", price: 4400, desc: "Luxury natural teakwood floater frame" },
      { id: "black_frame", name: "Minimalist Matte Black Frame", price: 3700, desc: "Sleek architectural matte black frame" }
    ],
    roomScale: 1.1
  },
  {
    id: "art-4",
    title: "The Flute of Vrindavan (Radha Krishna)",
    artist: "Devendra Joshi",
    artistBio: "Hailing from Jaipur, Devendra weaves classical Indian miniature aesthetics into grand contemporary compositions.",
    category: "Spiritual & Devotional",
    medium: "Natural Pigments & Acrylic on Stretched Canvas",
    style: "Neo-Classical Indian",
    orientation: "vertical",
    dimensions: "30\" x 45\" (76.2 x 114.3 cm)",
    year: 2024,
    price: 39500,
    originalPrice: 52000,
    discount: 24,
    image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=1200&q=80",
    description: "A soulful tribute to eternal divine love. Krishna playing the celestial flute beneath the Kadamba boughs, surrounded by peacock plumes and sacred lotuses, painted with jewel-like lapis lazuli and emerald greens.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8844",
    featured: false,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships rolled safely" },
      { id: "stretched", name: "Stretched Canvas", price: 1800, desc: "Ready to hang stretched canvas" },
      { id: "gold_frame", name: "Royal Antique Gold Leaf Frame", price: 5200, desc: "Handcrafted ornamental gold frame" },
      { id: "teak_frame", name: "Teakwood Frame", price: 4200, desc: "Solid teak floating frame" }
    ],
    roomScale: 1.05
  },
  {
    id: "art-5",
    title: "Monsoon Serenade over Alleppey",
    artist: "Thomas Kurian",
    artistBio: "Kerala-based watercolorist and plein-air artist known for atmospheric weather and reflections.",
    category: "Landscape & Scenery",
    medium: "Watercolor on 640gsm Arches 100% Cotton Rag",
    style: "Atmospheric Impressionism",
    orientation: "horizontal",
    dimensions: "42\" x 28\" (106.7 x 71.1 cm)",
    year: 2023,
    price: 34000,
    originalPrice: 42000,
    discount: 19,
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1200&q=80",
    description: "Dramatic monsoon clouds sweeping across emerald backwaters lined with coconut palms. Masterful wet-on-wet watercolor washes capturing the scent of fresh petrichor and shimmering tropical water.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8845",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships rolled safely" },
      { id: "stretched", name: "Acid-Free Gallery Mount", price: 2100, desc: "Archival mounting on rigid conservation board" },
      { id: "black_frame", name: "Matte Black Frame with 2\" White Mat", price: 4200, desc: "Museum-glass conservation frame with passepartout" }
    ],
    roomScale: 1.15
  },
  {
    id: "art-6",
    title: "Royal Rajputana: Pride of Marwar",
    artist: "Sunita Verma",
    artistBio: "Recipient of the National Lalit Kala Akademi award, Sunita brings majestic Rajasthani regal traditions to life.",
    category: "Figurative & Portrait",
    medium: "Oil & Real Gold Filigree on Stretched Linen",
    style: "Regal Figurative",
    orientation: "vertical",
    dimensions: "36\" x 54\" (91.4 x 137.2 cm)",
    year: 2024,
    price: 75000,
    originalPrice: 95000,
    discount: 21,
    image: "https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=1200&q=80",
    description: "An aristocratic Rajasthani noblewoman adorned in traditional Kundan jewelry, royal crimson silk poshak, and delicate veil. Exceptional details in the golden embroidery and soulful gaze reflecting courage and grace.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8846",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Art Tube)", price: 0, desc: "Ships rolled safely" },
      { id: "stretched", name: "Stretched Canvas", price: 2400, desc: "Stretched on solid kiln-dried pine wood" },
      { id: "gold_frame", name: "Royal Ornate Antique Gold Frame", price: 6500, desc: "Carved gold museum frame fitting a royal masterpiece" },
      { id: "teak_frame", name: "Handcrafted Teak Floating Frame", price: 5100, desc: "Rich warm timber finish" }
    ],
    roomScale: 1.25
  },
  {
    id: "art-7",
    title: "Urban Rhapsody: Mumbai Metro Twilight",
    artist: "Aarav Singhania",
    artistBio: "Architecture graduate turned contemporary artist exploring speed, urbanization, and nocturnal color rhythms.",
    category: "Modern & Contemporary",
    medium: "Palette Knife Heavy Impasto Oil on Canvas",
    style: "Contemporary Urban Expressionism",
    orientation: "horizontal",
    dimensions: "50\" x 30\" (127.0 x 76.2 cm)",
    year: 2024,
    price: 58000,
    originalPrice: 72000,
    discount: 19,
    image: "https://images.unsplash.com/photo-1549887534-1541e9326642?auto=format&fit=crop&w=1200&q=80",
    description: "Bold, energetic palette knife strokes portraying the vibrant night pulse of Marine Drive and Mumbai's skyline. Neon reflections on rainy asphalt contrast against the deep cobalt twilight sky.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8847",
    featured: false,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled)", price: 0, desc: "Rolled in heavy PVC tube" },
      { id: "stretched", name: "Stretched Canvas", price: 2200, desc: "Stretched on solid wood frame" },
      { id: "black_frame", name: "Sleek Matte Black Shadowbox", price: 4400, desc: "Dramatic contrast modern frame" }
    ],
    roomScale: 1.2
  },
  {
    id: "art-8",
    title: "Tree of Abundance: Contemporary Madhubani",
    artist: "Meera Devi & Sanjay Jha",
    artistBio: "Master artisans from Mithila, Bihar, blending generational GI-tagged folk traditions with contemporary scale.",
    category: "Traditional & Folk Art",
    medium: "Natural Mineral Colors & Acrylic on Canvas",
    style: "Madhubani / Mithila Folk Art",
    orientation: "square",
    dimensions: "36\" x 36\" (91.4 x 91.4 cm)",
    year: 2024,
    price: 28500,
    originalPrice: 36000,
    discount: 21,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1200&q=80",
    description: "An intricate celebration of the Tree of Life teeming with dancing peacocks, fish, sun and moon deities. Hand-drawn with bamboo nibs and colored with extracts of turmeric, indigo, and forest soot.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8848",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled)", price: 0, desc: "Ships safely rolled" },
      { id: "stretched", name: "Stretched Canvas", price: 1800, desc: "Stretched on wooden bars" },
      { id: "teak_frame", name: "Natural Sheesham/Teakwood Frame", price: 3900, desc: "Complements traditional Indian folk art" }
    ],
    roomScale: 1.05
  },
  {
    id: "art-9",
    title: "Serenade of the Lotus Pond",
    artist: "Priyanshu Patel",
    artistBio: "Vadodara fine arts alumni famous for tranquil botanicals and Japanese-inspired Zen simplicity.",
    category: "Modern & Contemporary",
    medium: "Acrylic, Oil & Gold Dust on Stretched Canvas",
    style: "Zen Minimalist",
    orientation: "horizontal",
    dimensions: "44\" x 30\" (111.8 x 76.2 cm)",
    year: 2024,
    price: 42000,
    originalPrice: 55000,
    discount: 24,
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80",
    description: "Blooming sacred pink lotuses floating gracefully on emerald and jade green waters, dusted with subtle gold highlights that glisten in natural daylight. Creates an aura of calm and mindfulness.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8849",
    featured: false,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled)", price: 0, desc: "Ships safely in tube" },
      { id: "stretched", name: "Stretched Canvas", price: 2000, desc: "Ready to hang" },
      { id: "teak_frame", name: "Light Oak / Teak Floater Frame", price: 4200, desc: "Enhances Zen aesthetic" }
    ],
    roomScale: 1.15
  },
  {
    id: "art-10",
    title: "Enlightenment Under the Bodhi Tree",
    artist: "Tenzin Norbu",
    artistBio: "Dharamshala trained Thangka artist who crafts meditative contemporary Buddhist art for world collectors.",
    category: "Spiritual & Devotional",
    medium: "Gouache & Gold Pigment on Treated Cotton Canvas",
    style: "Tibetan & Himalayan Modern Sacred",
    orientation: "vertical",
    dimensions: "32\" x 48\" (81.3 x 121.9 cm)",
    year: 2024,
    price: 52000,
    originalPrice: 65000,
    discount: 20,
    image: "https://images.unsplash.com/photo-1576769267415-9642010aa962?auto=format&fit=crop&w=1200&q=80",
    description: "Lord Buddha seated in the Dhyana Mudra (meditation posture) under the sprawling sacred Bodhi tree, surrounded by geometric mandalas and serene indigo aura. Conveys profound stillness and spiritual grace.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8850",
    featured: true,
    framingOptions: [
      { id: "rolled", name: "Unframed (Rolled in Sturdy Art Tube)", price: 0, desc: "Ships safely rolled" },
      { id: "stretched", name: "Stretched Canvas", price: 2100, desc: "Stretched on wooden bars" },
      { id: "gold_frame", name: "Antique Gilded Frame", price: 5400, desc: "Rich gold frame accentuating the sacred aura" },
      { id: "black_frame", name: "Satin Black Frame", price: 3900, desc: "Contemporary minimalist frame" }
    ],
    roomScale: 1.15
  },
  {
    id: "art-11",
    title: "Golden Meadow: Himalayan Autumn",
    artist: "Rameshwar Sen",
    artistBio: "Landscape specialist who spends months traversing the Garhwal and Kumaon Himalayas capturing alpine textures.",
    category: "Landscape & Scenery",
    medium: "Oil on Linen Board",
    style: "Realist Landscape",
    orientation: "horizontal",
    dimensions: "36\" x 24\" (91.4 x 61.0 cm)",
    year: 2023,
    price: 31000,
    originalPrice: 38000,
    discount: 18,
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
    description: "Golden alpine pastures in late autumn with snow-capped peaks in the background, warm afternoon shadows, and rustic shepherd trails. Exceptional depth and radiant color harmony.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8851",
    featured: false,
    framingOptions: [
      { id: "rolled", name: "Unframed", price: 0, desc: "Rolled in protective tube" },
      { id: "stretched", name: "Stretched Gallery Wrap", price: 1600, desc: "Ready to hang" },
      { id: "teak_frame", name: "Rustic Wood Frame", price: 3600, desc: "Warm natural wood finish" }
    ],
    roomScale: 1.05
  },
  {
    id: "art-12",
    title: "Chromatic Mirage #4",
    artist: "Zoya Alvi",
    artistBio: "Experimental abstract painter known for fluid dynamics, resin layers, and optical color vibrations.",
    category: "Abstract",
    medium: "Acrylic, Alcohol Inks & Resin on Birch Panel",
    style: "Fluid Abstract",
    orientation: "square",
    dimensions: "36\" x 36\" (91.4 x 91.4 cm)",
    year: 2024,
    price: 46000,
    originalPrice: 58000,
    discount: 21,
    image: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
    description: "Swirling currents of lapis, metallic copper, pearlescent white, and deep teal sealed under a high-gloss museum resin finish that mirrors glass. Changes color tone as you move across the room.",
    inStock: true,
    stockQuantity: 1,
    coaNumber: "GLR-2024-8852",
    featured: true,
    framingOptions: [
      { id: "stretched", name: "Gallery Ready (Cradled Panel)", price: 0, desc: "Sides finished in satin white, ready to hang" },
      { id: "black_frame", name: "Black Floater Frame", price: 3800, desc: "Sleek contemporary floater frame" },
      { id: "teak_frame", name: "Natural Teak Floater Frame", price: 4200, desc: "Warm wooden contrast" }
    ],
    roomScale: 1.1
  }
];
